### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/electric-cli/node_modules/node-sass/vendor'

### ISSUE THREAD

**Issue by jmnavarro** [electricjs/electric#95] opened 2017-12-13 12:03 UTC
Hey

I get this error when I run any electric command. I reinstalled, updated and refreshed everything, without success.

My versions are:

```
$ npm --version
5.5.1
$ node --version
v8.9.1
$ el --version
2.2.2
```

**Comment by jbalsas** [comment] 2017-12-13 12:10
Hey @jmnavarro, this is likely caused by a wrong `electric-cli` installation. Likely you don't have the proper permissions and the `sass` binary is not in place.

Could you try following one of these suggestions for [fixing npm permissions](https://docs.npmjs.com/getting-started/fixing-npm-permissions) (I personally have [Option2](https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-2-change-npms-default-directory-to-another-directory)) and install `electric-cli` again?

**Comment by rafaelfe** [comment] 2017-12-15 20:31
I run into this problem a couple of times. I had to set full permissions to my user in `/usr/local/lib/node_modules/electric-cli/` to fix this.

**Comment by jbalsas** [comment] 2017-12-20 11:03
Closing, I assume this is the case. @jmnavarro, please reopen if this is still failing for you!

**Closed by jbalsas** 2017-12-20 11:03 UTC
